name: Convert Excel to JSON

on:
  push:
    paths:
      - 'm_ranking Seghos 2025_26.xlsx'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Run conversion script
        run: python convert_excel_to_json.py

      - name: Commit updated JSON
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add ranking.json
          git commit -m 'Auto-update ranking.json from Excel'
          git push
